### ISSUE TITLE
RenderPath側とGomlとの連携

### ISSUE THREAD

**Issue by kyasbal-1994** [GrimoireGL/GrimoireJS#296]

**Comment by pnlybubbles** [comment]
詳細仕様欲しいです

**Comment by LimeStreem** [comment]
明日しゃべる

**Comment by LimeStreem** [comment]
# RenderPathの仕様

すべてのRendererの種類(現状ではviewportしかないが)は、内部にBufferSet及びRenderPathを持つ。

![renderer](https://cloud.githubusercontent.com/assets/6434708/13995773/ffe9c5b4-f16d-11e5-9636-b21ce1181547.png)

今回のこのissueはBufferSetに対する指定及びRenderPathの指定をGOML側からできるようにするためのものである。

RenderPathはRenderStageの配列により構成される。この配列はデフォルトでは通常のディファードレンダリング用の構成で初期化されるが、ユーザーの指定によってはこの順番を入れ替えられるようにもするべきである。

以下はその詳細設計である。

## 完成時のGOML

以下viewportより親、兄弟以下のタグを省略している。

### 提案1 (今までの書き方を採用する場合)

```xml
<viewport>
   <buffers>
      <buffer format="UBYTE" layout="RGB" allocator="rendererfit" name="main"/>
   </buffers>
   <path>
      <stage name="builtin.forward">
         <variables>
            <variable name="bias" value="0.12"/>
         </variables>
         <buffers>
           <buffer name="OUT" source="main"/>
         </buffers>
      </stage>
   </path>
</viewport>
```

ただし、path内のstageは現状で最も単純なレンダラでも9つ存在し、この記法だと冗長化してしまう。

### 提案2 (XML名前空間を用いる場合)
```xml
<viewport>
   <buffers>
      <buffer format="UBYTE" layout="RGB" allocator="rendererfit" name="main"/>
   </buffers>
   <path>
      <stage name="builtin.forward" v:bias="0.12" b:OUT="main"/>
   </path>
</viewport>
```

続きは明日書く。
