### ISSUE TITLE
CI Problem

### ISSUE THREAD

**Issue by pnlybubbles** [GrimoireGL/GrimoireJS#336]
* CircleCIがメモリ不足で落ちる。
* 原因はavaの並列babel。
* 解決策として先にlibとtestをバベってから、テストする。
* テストまではうまく行った。しかし、nycのlcovレポーターで落ちる。
* 解決策としてcoverageをjsonレポーターで吐き出し、ソースマップでリマップする。
* remap-istanbulを試したけどうまくいかず。
* 最終解決策としてCircleCIから離脱する。
* テスト・カバレッジ周りだけtravisにするのもあり(？

**Comment by LimeStreem** [comment]
travisだとCore側のテスト大体死にます

**Comment by pnlybubbles** [comment]
忘れてた
