### ISSUE TITLE
Componentの継承

### ISSUE THREAD

**Issue by moajo** [GrimoireGL/GrimoireJS#401]
gr.registerComponentでコンポーネントの継承を指定できるように。指定は文字列、NSIdentity,コンストラクタ指定のいずれか。
node.getComponentでポリモーフィズムを利用できる検索を実装する。
同様にnode.getCoomponentsを実装する。

```typescript
this.node.getComponent("Transform"); // 現在
this.node.getComponent(TransformComponent); // コンストラクタ関数によるフィルタリング
```

**Comment by kyasbal-1994** [comment]
getComponentsInChildren
getComponentも同様にフィルタリングできるべき。

**Comment by moajo** [comment]
同様のフィルタリングを適用した
