### ISSUE TITLE
0.12.0リリースに関するリファクタリング

### ISSUE THREAD

**Issue by kyasbal-1994** [GrimoireGL/GrimoireJS#403]
# リファクタリング

## インターフェース系の定義の簡略化(非破壊的)

- [x] 完了

現在、ファンクションかつオブジェクトな型を生成するために以下の3つを使っているがこれを解決する。

* オブジェクト部分のインターフェース
* 関数部分だけのインターフェース
* オブジェクト部分の実装

↓

* オブジェクト部分の実装
* 関数のインターフェース

**今まで**

```typescript
interface AInterfaceBase{
   // それ以外のオブジェクトのプロパティ
}
interface AInterface extends AInterfaceBase{
  // 関数の定義
}

class A implements AInterfaceBase{

}

// Aのインスタンスと関数を混ぜ合わせる処理 -> a

export default a as AInterface;
```

**これから**

```typescript
interface AInterfaceFunction{
   // 関数の定義
}

class A{
  // そのまま実装
}

// Aのインスタンスと関数を混ぜ合わせる処理 -> a

export default a as (A & AInterfaceFunction);
```

これにより、インターフェースを構成していたファイルをそれぞれ3つから1つに集約できるはず。
また、クラスには定義されているがインターフェース側への定義忘れでアクセスできないというような状況を修正する。

## getAttribute/getValueなどの名前の統一(破壊的変更)

- [x] 議論
- [x] 完了

**現状**
```typescript
   Component#getValue():any　
   Component#getAttribute():Attribute
   Node#getAttribute():any
 ```

**次期**
```typescript
   Component#getAttribute():any
   Component#getAttributeRaw():Attribute
   Node#getAttribute():any
```

統一したい。
**議論中**

## ComponentInterfaceの削除(破壊的変更)
いらないぽい
- [x] 議論
- [x] 完了

## ComponentのAttributeDeclaration(破壊的変更)

- [x] 完了

現状

```typescript
{
   converter:string;
   defaultValue:any;
}
```
次期
```typescript
{
   converter:string;
   default:any;
}
```

## Attributeのundefinedの扱い(破壊的変更)

- [x] 完了

* 属性の初期値がundefinedの場合は例外(この際、コンポーネント名を必ず出す)
* コンバーターにundefinedを入れたら例外(この際、コンバーター名、所属するノード名の情報を出す)
* コンバーターは変換できない場合undefinedを返す。

# 新機能

## インターフェース側からのattributeの変更の監視

- [x] 議論
- [x] 完了

**提案内容**

```typescript
gr("#main")("#aa").watch("属性名",(newAttr,oldAttr)=>
{

});
```

## Attribute#addObserverをAttribute#watchにリネーム(破壊的変更)

- [x] 完了

```typescript
Attribute#watch(func:(value:any,oldValue:any,attr:Attribute)=>void,immediate?:boolean);
```

## Attribute.convert

- [x] 完了

```typescript
public static convert(converterName:string,val:any):any;
```

特定のコンバーター名で変換するAPIを追加する。
指定したコンバーターが存在しなかった場合は例外

# ガイドライン系

## コンバーターのガイドライン

- [ ] これを記述

* コンバーターは**変換不可能な場合**、undefinedを返す
* 例外はコンバーターに指定されるべきオプション(attributesに指定される、`default`及び`converter`でもないもの)に不正があった場合のみ投げても良い
* コンバーターはundefiedを受け取ることはない

# Rleated PRs

#408
https://github.com/GrimoireGL/grimoire.gl-example/pull/1
https://github.com/GrimoireGL/grimoirejs-fundamental/pull/7
https://github.com/GrimoireGL/grimoirejs-gltf/pull/2
https://github.com/GrimoireGL/grimoirejs-basic/pull/1

**Comment by moajo** [comment]
属性監視はAttribute.addObserverではダメですか？

**Comment by pnlybubbles** [comment]
ないぶに関して漢壁には把握していないですが、`Component.getAttribute("aaa").addObserver(() => {})`となっている部分が多々あったので、これと同様にNodeでもやりたいと思ったのですが、既に`Node.getAttribute`があるのでどうするのが吉なのかなあと。
ちなみにwatch案はvue由来です。

**Comment by kyasbal-1994** [comment]
@moajo それはまずAttributeがすでに定義されている状態でないととれないのでは?

**Comment by moajo** [comment]
監視しようとしてる属性が存在しない状況がある？

**Comment by kyasbal-1994** [comment]
あり得る。マテリアルとかの値なら。

**Comment by pnlybubbles** [comment]
getAttributeしてしまったじてんでAttributeをつくってしまうのはどうでしょう

**Comment by moajo** [comment]
typoによるバグが多発しそうだから嫌
