### ISSUE TITLE
optionalComponentの属性をノードに露出させたい

### ISSUE THREAD

**Issue by moajo** [GrimoireGL/GrimoireJS#416]
すべてのコンポーネントの属性はノードに露出する。

属性のNSIdentityが重複した場合、ノードから操作したときは、**対象となるすべての属性が操作される。**

個別に操作したいときは、componentのインスタンスから別個に操作する。

**Comment by moajo** [comment]
ノードに同一コンポーネントが複数存在する場合。

+ setAttributeするときは、その時点で存在するすべての属性に対して行う。
  + ただし、その時点で当該属性が存在しない場合は、その後に追加される最初の属性にたいして行う？？
+ getAttributeするときは、例外。
+ watchするときは、その時点で存在するすべての属性に対して行う。
  + ただし、watch時点で当該属性が存在しない場合(lazy watch)その後に追加される最初の属性にたいして行う？？

**Comment by kyasbal-1994** [comment]
`GomlNode`による操作と、`GomlInterface`にしっかり分解して考える必要があると思う。
`GomlNode`はコンポーネント単体で動作するように書けば、ユーザーがどのような扱いをしようと、コンポーネント単体としての動作は保持されるべきであって、一方で`GomlInterface`側はクエリ的な考え方が入っている概念であるから複数個弄れるというのは自然ではある。

したがって、`GomlInterface`の場合は、以下のような仕様がいいのでは?

* setAttributeするときは、その時点で存在する全ての同名の属性に対して行う。
　* ただし、その時点で当該属性が存在しない場合、**つまり、setAttributeした値を受け取りうるコンポーネントが後から追加された場合**(この理解で合ってる?)があった場合は、初期値の解決のみに用いられる。  
(GOMLの値(appendされた時のコンポーネントの属性による値) > ユーザーのノードにsetAttributeした値 > nodeのデフォルト値 > componentのデフォルト値)

* getAttributeするときは例外。ただしgetAttributesを実装して配列で取得するものはあった方が良いかも。

* watchするときは、その時点で存在する全てに対して行う。
  * 後から追加されたコンポーネントの当該属性に関しても同様。

`GomlNode`のgetAttribute/setAttributeは廃止をすべき。(内部的な利用は構わないが、ユーザーからの利用はすべてgetComponentしてからの利用を目指す)

そもそも、同名の属性を持ちうる別のコンポーネントが追加された場合など、属性名から全て判断する場合、コンポーネントの外部的要因で、コンポーネントが存在する値の取得がうまく行かない可能性がある。

**Comment by moajo** [comment]
(GOMLの値(appendされた時のコンポーネントの属性による値) > ユーザーのノードにsetAttributeした値 は逆では？

**Comment by kyasbal-1994** [comment]
いや、append時にユーザーの指定でoptionalComponent自身が属性を持っていた場合は、ノードに対する操作よりも優先されるべきでは?

**Comment by moajo** [comment]
ノードの属性が遅延設定されていた場合、それは将来そのノードに追加されるであろうコンポーネントの挙動を制御するためのものなので、追加された時点でコンポーネントが持っている属性より優先されるべき。

**Comment by kyasbal-1994** [comment]
なんかちゃんと把握してないかも。明らかに意図せぬバグを生みそう

**Comment by moajo** [comment]
GomlNodeに**異なるコンポーネントの同名属性が複数存在するとき**
属性名のみでの`get,set,watch`は例外。
FQNでの`get,set,watch`は通る。

GomlNodeに**同じコンポーネントが複数存在するとき**
属性名のみでもFQNでも`set,watch`は、**すべての属性に対して。**`get`は例外。

**Comment by kyasbal-1994** [comment]
これは閉じるべきもの?
