### ISSUE TITLE
NSIdentityの自動生成

### ISSUE THREAD

**Issue by moajo** [GrimoireGL/GrimoireJS#424]
改善案：
NSIdentityをパッケージ名から自動生成する。
npmのurlを基本NSとして用いる。

各種オブジェクトに割り振られるNSのスキーマは以下の通り。

+ GomlNode
  + [基本NS]|[ノード名]
+ Component
  + [基本NS]|[コンポーネント名]
+ Attribute
  + [基本NS]|[コンポーネント名].[属性名]

これによって同一NSを持つ対象は必ず一種類しか存在しないことが保証される。
optionalComponentの属性露出における問題の解決となる。

**Comment by moajo** [comment]
This is an implementation plan of the feature to automatically resolve the namespace.

1. Change `index.ts` generated by cauldron and notify `GrimoireInterface` of namespace of plugin to be registered before calling `main.ts`.
2. When calling `loadTask` of plugin, GrimoireInterface passes an interface mocking `registerComponent`, ` registerNode`  and other registration function as an argument. 
The registration function internally replace the namespace of the object to that notified in advance, and recalls the original registration function of GrimoireInterface.

As a result, the contents of the `main.ts` of the plugin are changed as follows.
 ### before:

```javascript
export default () => {
  GrimoireInterface.register(async () => {
    const _$ns = GrimoireInterface.ns("HTTP://GRIMOIRE.GL/NS/DEFAULT");
    GrimoireInterface.registerComponent(_$ns("AssetLoadingManager"), AssetLoadingManagerComponent);
```

### after:

```javascript
export default () => {
  GrimoireInterface.register(async (gr) => {
    gr.registerComponent("AssetLoadingManager", AssetLoadingManagerComponent);
```

**Comment by kyasbal-1994** [comment]
LGTM

**Comment by moajo** [comment]
I basically implemented it as suggested above.
But I noticed that the interface can be made more simplify.
When resolving loadTask, GrimoireInterface has the namespace of the plugin as internal state, and the registration function replaces the default namespace until the loadTask finished.
By doing this, the loadTask no longer needs to receive mock object.
