### ISSUE TITLE
converterに付加情報を持たせる

### ISSUE THREAD

**Issue by moajo** [GrimoireGL/GrimoireJS#426]
lazy evaluationなどはAttributeに依存するというより、converterに依存するプロパティです。
このような**converterに依存し、Attributeに影響を及ぼすプロパティ**があることを考え、converterをただの関数ではなくプロパティをもつオブジェクトにするべき。

**Comment by kyasbal-1994** [comment]
具体例欲しいです

**Comment by moajo** [comment]
late-evaluationとかです。
ただ、registerConverterの引数を関数とオブジェクトの両方取れるようにすれば、後方互換性は保てるはず。

**Comment by moajo** [comment]
```
{
  param:{
    late:true
  }
  convert:function(val){
  }
}
```

**Comment by kyasbal-1994** [comment]
オブジェクトとして登録した方がよさそう。
だけど、attrという名前は語弊があると思う。

```
{
   parameters:{late:true},
   convert:function(val){}
}
```

ただ、この場合thisがこのオブジェクトでなくAttributeなのは直感的じゃないな。

**Comment by moajo** [comment]
もともとthisのバインドが直感的とは言い難い気が、、
いっそバインドをやめて引数として受け取る？
```javascript
  convert:function(val,attr){}
```

**Comment by kyasbal-1994** [comment]
それはありだと思う

**Comment by kyasbal-1994** [comment]
これは閉じるべきもの?
