### ISSUE TITLE
プラグイン推奨仕様

### ISSUE THREAD

**Issue by moajo** [GrimoireGL/GrimoireJS#428]
プラグインはcauldronでテンプレートが生成される。
テンプレ生成時にディレクトリ構成をある程度標準化する。

/-
  |- src
    |- components:この中にある**Component.js(.ts)
    |- converters:この中にある**Converter.js(.ts)
    |- nodes.js(.ts)//ノードはこの中

nodes.jsでは、以下の用にノード定義のオブジェクトをエクスポート
```javascript
export default {
  NodeName:{
    components:[],
    default:{attr:0}
  }
}
```

**Comment by kyasbal-1994** [comment]
テンプレートとなるプロジェクトのボイラープレートはいかにアップロード済み
https://github.com/GrimoireGL/ts-boilerplate

**Comment by moajo** [comment]
tsテンプレートは実装済

**Comment by kyasbal-1994** [comment]
参考:https://github.com/GrimoireGL/GrimoireJS/issues/429

**Comment by kyasbal-1994** [comment]
https://github.com/GrimoireGL/js-boilerplate
