### ISSUE TITLE
チュートリアルページのコードでエラーが発生する

### ISSUE THREAD

**Issue by fullmated** [GrimoireGL/GrimoireJS#570]
https://grimoire.gl/guide/1_essentials/02_introduction.html
のRotateコンポーネントの説明において、チュートリアルのページには以下のようなコードが書かれている。
```js
$update:function(){
    this.phi += this.getValue("speed");
    this.node.setAttribute("rotation",this.phi + "," + this.phi + "," + this.phi);
  }
```
しかしこのまま書くとコンソールでエラーが吐き出される。[SAMPLE](https://grimoiregl.github.io/grimoire.gl-example/#guide-05)の通りに書いたら正常に動作した。
```js
$update:function(){
    this.phi += this.getAttribute("speed");
    this.node.setAttribute("rotation",this.phi + "," + this.phi + "," + this.phi);
}
```
ページに書かれたコードが間違っていたのでしょうか。それとも、私の環境の問題でしょうか。

Chrome バージョン: 65.0.3325.181（Official Build） （64 ビット）

**Comment by cx20** [comment]
チュートリアルのコードが古いようですね。Grimiore.js v0.12.0 以降では `getValue` ではなく `getAttribute` を使う必要があるようです。

https://github.com/GrimoireGL/GrimoireJS/issues/403

> getAttribute/getValueなどの名前の統一(破壊的変更)

**Comment by kyasbal** [comment]
チュートリアル直さないといけなそうですね。コメントありがとうございます!

**Comment by fullmated** [comment]
@cx20 迅速に教えていただきありがとうございます!
@kyasbal-1994 よろしくお願いいたします! また何かあったら報告いたします。
