### ISSUE TITLE
Create ambient declaration of ammo.js

### ISSUE THREAD

**Issue by kyasbal-1994** [GrimoireGL/GrimoireJS#67]

**Comment by ButzYung** [comment]
Not strictly related, but I wonder if you guys will consider making a web worker version of ammo.js, which means processing physics in a separated thread.

I am using the current v2.1.2 jThree, and obviously the physics part is a bottleneck of performance. When using MMD models that involve a lof of physics, frame rate drops sharply. My workaround is to lower the value of "maxSubSteps" in jThree.MMD.js to 2 or even 1, but I suppose it will lower the accuracy of physics calculation as well.

**Comment by LimeStreem** [comment]
I want to use ammo.js in Web Worker. But, I wonder it takes a lot of time to implement. Therefore,I'm planning to implement ammo.js in basic way, then if I complete other tasks I should do first, I will move the code into Web Worker.
